/**
 * Signature-based stealth key derivation (recoverable from the wallet).
 *
 * Instead of random keys stored separately, we derive the stealth spending and
 * viewing keys deterministically from a signature produced by the wallet. The
 * wallet signs a fixed, app-specific message; the signature becomes the entropy.
 *
 *   Same wallet  -> same signature -> same stealth keys, every time.
 *
 * This means the stealth keys are recoverable from the seed phrase alone (via the
 * signing address), so clearing localStorage no longer loses stealth funds. This
 * is the approach used by production stealth-address wallets.
 *
 * Educational/testnet note: the derived keys are still cached in localStorage for
 * convenience, but they can always be regenerated by signing again.
 */

import { ethers } from "ethers";
import { secp256k1 } from "@noble/curves/secp256k1.js";
import { keccak_256 } from "@noble/hashes/sha3.js";
import { bytesToHex, hexToBytes } from "@noble/hashes/utils.js";
import { StealthKeys } from "./stealth";

const STORAGE_KEY = "stealth_keys";

// Fixed message the wallet signs to derive stealth keys. Changing this string
// changes everyone's derived keys, so it is versioned and must stay stable.
const DERIVATION_MESSAGE =
  "AnonWallet Stealth Keys\nSign to generate your stealth meta-address.\nVersion: 1";

const CURVE_ORDER = secp256k1.Point.Fn.ORDER;

function bytesToHex0x(b: Uint8Array): string {
  return "0x" + bytesToHex(b);
}

// Map arbitrary 32-byte entropy to a valid secp256k1 private scalar.
function entropyToPrivKey(entropy32: Uint8Array): Uint8Array {
  let scalar = BigInt("0x" + bytesToHex(entropy32)) % CURVE_ORDER;
  if (scalar === BigInt(0)) scalar = BigInt(1);
  return hexToBytes(scalar.toString(16).padStart(64, "0"));
}

/**
 * Derive stealth keys from a signature string (65-byte hex signature).
 * Pure function — deterministic given the signature.
 */
export function deriveStealthKeysFromSignature(signature: string): StealthKeys {
  const sigBytes = ethers.getBytes(signature);

  // two independent entropy streams from the one signature
  const spendEntropy = keccak_256(sigBytes);
  const viewEntropy = keccak_256(new Uint8Array([...sigBytes, 0x01]));

  const spendingPrivateKey = entropyToPrivKey(spendEntropy);
  const viewingPrivateKey = entropyToPrivKey(viewEntropy);

  const spendingPublicKey = secp256k1.getPublicKey(spendingPrivateKey, true);
  const viewingPublicKey = secp256k1.getPublicKey(viewingPrivateKey, true);

  return {
    spendingPrivateKey: bytesToHex0x(spendingPrivateKey),
    spendingPublicKey: bytesToHex0x(spendingPublicKey),
    viewingPrivateKey: bytesToHex0x(viewingPrivateKey),
    viewingPublicKey: bytesToHex0x(viewingPublicKey),
    stealthMetaAddress:
      "st:eth:0x" + bytesToHex(spendingPublicKey) + bytesToHex(viewingPublicKey),
  };
}

/**
 * Sign the derivation message with a private key and derive stealth keys.
 * Caches the result so we don't re-sign every time.
 */
export async function deriveAndStoreStealthKeys(
  signingPrivateKey: string
): Promise<StealthKeys> {
  const signer = new ethers.Wallet(signingPrivateKey);
  const signature = await signer.signMessage(DERIVATION_MESSAGE);
  const keys = deriveStealthKeysFromSignature(signature);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(keys));
  return keys;
}

/** Returns cached stealth keys if present, else null (does not derive). */
export function getStealthKeys(): StealthKeys | null {
  try {
    const existing = localStorage.getItem(STORAGE_KEY);
    return existing ? JSON.parse(existing) : null;
  } catch {
    return null;
  }
}

/**
 * Get cached keys, or derive+store them from the signing key if absent.
 * Pass the private key of the address you want to anchor stealth keys to
 * (typically Address #0).
 */
export async function getOrDeriveStealthKeys(
  signingPrivateKey: string
): Promise<StealthKeys> {
  const cached = getStealthKeys();
  if (cached) return cached;
  return deriveAndStoreStealthKeys(signingPrivateKey);
}

export function clearStealthKeys(): void {
  localStorage.removeItem(STORAGE_KEY);
}